spring:
  config:
    import:
      - classpath:connection.yaml
      - classpath:oauth-google-resource.yaml
  application:
    name: spring-resource-server
  jpa:
      database: postgresql
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  sql:
    init:
      platform: postgresql

server:
  servlet:
    context-path: /spring-resource-server

logging:
    level:
      org:
        hibernate:
          engine:
            jdbc:
              env:
                internal:
                  LobCreatorBuilderImpl: error
        springframework:
          jdbc:
            datasource:
              init:
                ScriptUtils: debug
          security: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jasypt:
    encryptor:
      password: springboot
