spring:
  config:
    import: classpath:connection.yaml
  application:
    name: spring-resource-server
  jpa:
      database: postgresql
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  sql:
    init:
      platform: postgresql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${WSO2IS_URL:https://localhost:9443}/oauth2/token


server:
  servlet:
    context-path: /spring-resource-server

logging:
    level:
      org:
        hibernate:
          engine:
            jdbc:
              env:
                internal:
                  LobCreatorBuilderImpl: error
        springframework:
          jdbc:
            datasource:
              init:
                ScriptUtils: debug
          security: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jasypt:
    encryptor:
      password: springboot
